### ISSUE TITLE
Vou tentar traduzir todas as versões do jogo.

### ISSUE THREAD

**Issue by satoon10** [RafaRed/JackboxPartyPack-Localization#64]
Joguei com meus amigos, e foi horrível, os erros da tradução automática acabou confundindo os outros. E outros jogos nem estavam traduzidos completamente. Alguém tem os arquivos .jet para eu retraduzir do começo? No momento tenho apenas os arquivos do 7.

**Comment by RafaRed** [comment]
olá @satoon10, agradeço seu interesse.
Você pode encontrar os arquivos originais no en-us (default)
https://github.com/satoon10/JackboxPartyPack-Localization/tree/main/en-us%20(default)

lembrando que alguns jogos como:
Drawful 
Quiplash 
SplitTheRoom 

Já foram revisados.

**Comment by satoon10** [comment]
Obrigado, estou traduzindo as palavras do Blanky Blanky, e são mais de 100 mil linhas. Vai demorar um pouco. Parei na linha 3700, devo colocar logo no github?

**Comment by RafaRed** [comment]
Pode sim, é bom que ja fica traduzido no projeto.
Mas se preferir enviar de uma vez só, tudo bem. :)

**Comment by satoon10** [comment]
Não sei se é um problema no meu jogo, mas o "Blather Round", "Champ'd UP", e o "The Devils And The Details", só estão funcionando com os arquivos originais do jogo, alguma ideia do que pode ser?

**Comment by RafaRed** [comment]
Exato, provavelmente são caracteres especiais, e acentos.
Algum variável pode ter sido substituída durante a tradução, mas acredito fortemente que seja um problema com acentos, pois ja tive problema com eles.

**Comment by satoon10** [comment]
Você já considerou, editar os arquivos SWF? Os textos que não aparecem nos arquivos JET ou JSON estão lá, incluindo as legendas

**Comment by RafaRed** [comment]
Exato, mas acho que é um material mais difícil de traduzir, pois, exige mais conhecimento.
Caso se disponha, pode adicionar sim.

**Comment by satoon10** [comment]
Consegui traduzir todas as legendas do "Champ'd UP", esse arquivo fica em "JPP7\games\WorldChampions\TalkshowExport\project\data\start.swf"
[Download Pelo WeTransfer](https://we.tl/t-bstIyF95Ww)

**Comment by satoon10** [comment]
Opa, tem como você criar as pastas pra eu dar upload nas legendas" O arquivo têm que ficar aqui "JPP7/games\WorldChampions\TalkshowExport\project\data\"

**Comment by satoon10** [comment]
Oi, acabei de traduzir vários arquivos swf novos do Champ'Up. Acredito que foram todos os arquivos swf que eu podia traduzir.
A pasta deles fica em "JPP7\games\WorldChampions\swf". Ainda não sei bem como criar pastas, então se puder criar, eu darei upload dos arquivos lá.

Esses são os arquivos que editei
![vWbOBiT](https://user-images.githubusercontent.com/60121690/175059869-588c2bb3-1355-4a4b-9025-7aab5e1402cd.png)

Abaixo segue os textos que traduzi
![6YMsLI0](https://user-images.githubusercontent.com/60121690/175059620-245b73eb-63db-4a20-849c-1b6ba0afba71.png)
![mVB0oBp](https://user-images.githubusercontent.com/60121690/175059799-f6113f66-8fa0-4d5d-a864-6248f3365a7c.png)
![c0NNU47](https://user-images.githubusercontent.com/60121690/175059817-9236244e-b24d-4a01-87cb-97e1eece46e7.png)
![Ezd22Cu](https://user-images.githubusercontent.com/60121690/175059829-42b492b3-dbe5-48d0-9222-5974ee7cc49f.png)
![MUKwBnU](https://user-images.githubusercontent.com/60121690/175059845-8b06ea88-6847-4ba8-8251-2d3b85686b90.png)

PS.: Tem uns erros de recorte em alguns textos, não sei como resolver, perdão!

**Comment by RafaRed** [comment]
Opa muito bom, estarei aceitando.
