### ISSUE TITLE
Queria instalar a tradução (mesmo que seja automatica)

### ISSUE THREAD

**Issue by cur1ousfox** [RafaRed/JackboxPartyPack-Localization#71]
Olá gostaria de saber como se instala a tradução.  Pensei que era so colar os arquivos que estao nas pastas daqui nas pastas do jogo mas as pastas nao batem. Poderia me ajudar?

**Comment by RafaRed** [comment]
Olá @cur1ousfox, o projeto ainda precisa de uma documentação melhor para instalação, mas a princípio você precisa baixar todo projeto através do link: https://github.com/RafaRed/JackboxPartyPack-Localization/archive/refs/heads/main.zip

Em seguida, você deve procurar o jogo que você quer, exemplo:
Fibbage, do jackbox party pack 1.
você poderá encontrar a tradução desse jogo na pasta:
"pt-br/The Jackbox Party Pack 1/games/content"
Procure esses mesmo arquivos no seu jogo, que devem estar em um caminho semelhante
"The Jackbox Party Pack 1/games/Fibbage/content/" e os subistitua.

Lembrando que nem total traduções foram totalmente revisadas, mas espero que possa melhorar a experiencia sua com seus amigos.
Se ainda restar dúvidas, ou a explicação não foi muito clara em alguma parte, pode entrar em contato.
